ALTER TABLE sessions 
ADD COLUMN IF NOT EXISTS ai_score FLOAT,
ADD COLUMN IF NOT EXISTS physics_score FLOAT,
ADD COLUMN IF NOT EXISTS unified_score FLOAT,
ADD COLUMN IF NOT EXISTS ai_explanation JSONB,
ADD COLUMN IF NOT EXISTS verification_status VARCHAR(50);
