"""
VeraProof AI - Lightsail Stack
AWS Lightsail Container Service + Lightsail Database
All-in-one cost-effective deployment
"""
from aws_cdk import (
    Stack,
    aws_lightsail as lightsail,
    aws_s3 as s3,
    aws_cognito as cognito,
    aws_iam as iam,
    aws_ssm as ssm,
    CfnOutput,
    RemovalPolicy
)
from constructs import Construct
import json


class VeraproofLightsailStack(Stack):
    """Lightsail Container + Database stack"""
    
    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        stage: str,
        artifacts_bucket: s3.Bucket,
        branding_bucket: s3.Bucket,
        user_pool: cognito.UserPool,
        **kwargs
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)
        
        # Lightsail Container Service size based on stage
        # FREE TIER: Micro (0.25 vCPU, 1GB) - 1 node - FREE for 3 months, then $10/month
        power_map = {
            "dev": "nano",      # 0.25 vCPU, 512MB - $7/month (no free tier)
            "staging": "micro",  # 0.25 vCPU, 1GB - $10/month (FREE for 3 months)
            "prod": "micro"      # 0.25 vCPU, 1GB - $10/month (FREE for 3 months)
        }
        
        scale_map = {
            "dev": 1,
            "staging": 1,
            "prod": 1  # Only 1 node qualifies for free tier
        }
        
        # Lightsail Database size based on stage
        # FREE TIER: Micro (1 vCPU, 1GB, 40GB) - FREE for 3 months, then $15/month
        db_bundle_map = {
            "dev": "micro_2_0",     # 1 vCPU, 1GB, 40GB SSD - $15/month (FREE for 3 months)
            "staging": "micro_2_0",  # 1 vCPU, 1GB, 40GB SSD - $15/month (FREE for 3 months)
            "prod": "micro_2_0"      # 1 vCPU, 1GB, 40GB SSD - $15/month (FREE for 3 months)
        }
        
        # Lightsail Database (PostgreSQL)
        # Note: Password will be auto-generated by Lightsail and can be retrieved via AWS CLI
        self.database = lightsail.CfnDatabase(
            self,
            f"Veraproof-Lightsail-Database-{stage}",
            relational_database_name=f"veraproof-db-{stage}",
            relational_database_bundle_id=db_bundle_map.get(stage, "micro_2_0"),
            relational_database_blueprint_id="postgres_16",
            master_database_name="veraproof",
            master_username="veraproof_admin",
            rotate_master_user_password=True,  # Auto-generate secure password
            publicly_accessible=False,  # Only accessible from Lightsail containers
            backup_retention=True,
            preferred_backup_window="03:00-04:00",  # 3-4 AM IST
            preferred_maintenance_window="mon:04:00-mon:05:00",  # Monday 4-5 AM IST
            tags=[
                {
                    "key": "Project",
                    "value": "VeraProof-AI"
                },
                {
                    "key": "Stage",
                    "value": stage
                }
            ]
        )
        
        # Lightsail Container Service
        # Note: Container deployment will be done via GitHub Actions after initial creation
        self.container_service = lightsail.CfnContainer(
            self,
            f"Veraproof-Lightsail-Container-{stage}",
            service_name=f"veraproof-api-{stage}",
            power=power_map.get(stage, "micro"),
            scale=scale_map.get(stage, 1),
            is_disabled=False,
            tags=[
                {
                    "key": "Project",
                    "value": "VeraProof-AI"
                },
                {
                    "key": "Stage",
                    "value": stage
                }
            ]
        )
        
        # IAM role for Lightsail to access S3
        lightsail_role = iam.Role(
            self,
            f"Veraproof-Lightsail-Role-{stage}",
            role_name=f"veraproof-lightsail-role-{stage}",
            assumed_by=iam.ServicePrincipal("lightsail.amazonaws.com"),
            description=f"IAM role for Lightsail container service - {stage}"
        )
        
        # Grant S3 permissions
        artifacts_bucket.grant_read_write(lightsail_role)
        branding_bucket.grant_read_write(lightsail_role)
        
        # Grant SSM Parameter Store read permission
        lightsail_role.add_to_policy(
            iam.PolicyStatement(
                actions=[
                    "ssm:GetParameter",
                    "ssm:GetParameters",
                    "ssm:GetParametersByPath"
                ],
                resources=[
                    f"arn:aws:ssm:{self.region}:{self.account}:parameter/veraproof/{stage}/*"
                ]
            )
        )
        
        # Store database connection info in SSM for backend to use
        ssm.StringParameter(
            self,
            f"Veraproof-DB-Endpoint-{stage}",
            parameter_name=f"/veraproof/{stage}/database/endpoint",
            string_value=self.database.attr_database_arn.split(":")[-1],  # Extract endpoint from ARN
            description=f"Lightsail database endpoint for {stage}",
            tier=ssm.ParameterTier.STANDARD
        )
        
        ssm.StringParameter(
            self,
            f"Veraproof-DB-Port-{stage}",
            parameter_name=f"/veraproof/{stage}/database/port",
            string_value="5432",  # PostgreSQL default port
            description=f"Lightsail database port for {stage}",
            tier=ssm.ParameterTier.STANDARD
        )
        
        # API URL (Lightsail provides a default URL via attr_url)
        self.api_url = self.container_service.attr_url
        
        # Outputs
        CfnOutput(
            self,
            f"Lightsail-Container-Service-{stage}",
            value=self.container_service.service_name,
            description=f"Lightsail container service name for {stage}",
            export_name=f"Veraproof-Lightsail-Container-{stage}"
        )
        
        CfnOutput(
            self,
            f"Lightsail-Database-Name-{stage}",
            value=self.database.relational_database_name,
            description=f"Lightsail database name for {stage}",
            export_name=f"Veraproof-Lightsail-Database-{stage}"
        )
        
        CfnOutput(
            self,
            f"Lightsail-API-URL-{stage}",
            value=self.api_url,
            description=f"Lightsail API URL for {stage}",
            export_name=f"Veraproof-Lightsail-API-URL-{stage}"
        )
        
        CfnOutput(
            self,
            f"Lightsail-Database-Endpoint-{stage}",
            value=self.database.attr_database_arn,
            description=f"Lightsail database ARN for {stage}",
            export_name=f"Veraproof-Lightsail-DB-ARN-{stage}"
        )
        
        CfnOutput(
            self,
            f"Lightsail-Database-Port-{stage}",
            value="5432",
            description=f"Lightsail database port for {stage}",
            export_name=f"Veraproof-Lightsail-DB-Port-{stage}"
        )
        
        CfnOutput(
            self,
            f"Lightsail-IAM-Role-ARN-{stage}",
            value=lightsail_role.role_arn,
            description=f"IAM role ARN for Lightsail - {stage}",
            export_name=f"Veraproof-Lightsail-Role-ARN-{stage}"
        )
